# Generated by Django 3.1.7 on 2021-04-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_auto_20210331_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='limit_value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
