# Generated by Django 3.1.7 on 2021-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0004_pollutant_limit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='colors',
            field=models.CharField(default='#000000', max_length=30),
        ),
    ]
