# Generated by Django 3.1.7 on 2021-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0005_country_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='colors',
            new_name='color',
        ),
    ]
