# Generated by Django 3.1.7 on 2021-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='image',
            field=models.ImageField(upload_to='my_apps'),
        ),
    ]
