# Generated by Django 3.1.7 on 2021-03-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210330_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'ordering': ['name'], 'verbose_name_plural': 'my apps'},
        ),
    ]
