# Generated by Django 3.1.7 on 2021-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210330_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default='/air', max_length=30),
            preserve_default=False,
        ),
    ]
